Correct Class Definitions
We are observing the following error when initially configuring alertmanager with the updated module...

```
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Syntax error at 'String'; expected ')' at /puppet/src/environments/production/modules/prometheus/manifests/alerts.pp:12 on node redacted.example.net 
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Basically this is an issue with the class definition for alerts and seems pretty easily fixed since defaults are all defined anyway...